version: 2

sources:
  - name: jaffle_shop
    database: raw
    tables:
      - name: customers
      - name: orders

  - name: stripe
    database: raw
    tables:
      - name: payment

  - name: raw
    database: ticket_tailor
    tables:
      - name: orders

  - name: learn_stripe
    database: raw
    tables:
      - name: refunds

  - name: raw
    database: learn_stripe
    tables:
      - name: charges      